"""change_birthday_to_date_type

Revision ID: 207dd43d01f0
Revises: 311dade1f6bc
Create Date: 2025-08-27 21:04:17.279283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207dd43d01f0'
down_revision = '311dade1f6bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Since we're in development, simply drop and recreate the table with correct schema
    # WARNING: This will delete all existing data
    
    op.drop_index(op.f('ix_notion_team_name'), table_name='notion_team')
    op.drop_index(op.f('ix_notion_team_discord_user_id'), table_name='notion_team')
    op.drop_table('notion_team')
    
    # Recreate with correct birthday type
    op.create_table('notion_team',
    sa.Column('notion_page_id', sa.String(length=255), nullable=False),
    sa.Column('notion_database_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('position', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('birthday', sa.DateTime(timezone=True), nullable=True),  # Now datetime
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('discord_user_id', sa.String(length=20), nullable=True),
    sa.Column('discord_message_id', sa.String(length=20), nullable=True),
    sa.Column('discord_channel_id', sa.String(length=20), nullable=True),
    sa.Column('notion_url', sa.String(length=500), nullable=True),
    sa.Column('notion_properties', sa.JSON(), nullable=True),
    sa.Column('last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notion_page_id')
    )
    op.create_index(op.f('ix_notion_team_discord_user_id'), 'notion_team', ['discord_user_id'], unique=False)
    op.create_index(op.f('ix_notion_team_name'), 'notion_team', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert birthday column back to VARCHAR
    op.alter_column('notion_team', 'birthday',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               nullable=False)
    # ### end Alembic commands ###