"""Add notion_task_id field

Revision ID: 2843ea3824fc
Revises: a558643327c9
Create Date: 2025-08-26 14:36:59.753818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2843ea3824fc'
down_revision = 'a558643327c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notion_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notion_task_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_notion_tasks_notion_task_id'), ['notion_task_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notion_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notion_tasks_notion_task_id'))
        batch_op.drop_column('notion_task_id')

    # ### end Alembic commands ###