"""add_notion_team_table

Revision ID: 311dade1f6bc
Revises: 2843ea3824fc
Create Date: 2025-08-27 20:55:04.960348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '311dade1f6bc'
down_revision = '2843ea3824fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notion_team',
    sa.Column('notion_page_id', sa.String(length=255), nullable=False),
    sa.Column('notion_database_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('position', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('birthday', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('discord_user_id', sa.String(length=20), nullable=True),
    sa.Column('discord_message_id', sa.String(length=20), nullable=True),
    sa.Column('discord_channel_id', sa.String(length=20), nullable=True),
    sa.Column('notion_url', sa.String(length=500), nullable=True),
    sa.Column('notion_properties', sa.JSON(), nullable=True),
    sa.Column('last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notion_page_id')
    )
    op.create_index(op.f('ix_notion_team_discord_user_id'), 'notion_team', ['discord_user_id'], unique=False)
    op.create_index(op.f('ix_notion_team_name'), 'notion_team', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notion_team_name'), table_name='notion_team')
    op.drop_index(op.f('ix_notion_team_discord_user_id'), table_name='notion_team')
    op.drop_table('notion_team')
    # ### end Alembic commands ###