"""Add Notion models

Revision ID: 4e1cfbea89e9
Revises: a6a7cb1466f0
Create Date: 2025-08-26 14:17:58.235176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e1cfbea89e9'
down_revision = 'a6a7cb1466f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notion_databases',
    sa.Column('notion_database_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('database_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notion_url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_sync', sa.Boolean(), nullable=False),
    sa.Column('sync_interval', sa.Integer(), nullable=False),
    sa.Column('properties_schema', sa.JSON(), nullable=False),
    sa.Column('default_channel_id', sa.String(length=20), nullable=True),
    sa.Column('notification_channel_id', sa.String(length=20), nullable=True),
    sa.Column('last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('sync_errors', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notion_database_id')
    )
    with op.batch_alter_table('notion_databases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notion_databases_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notion_databases_id'), ['id'], unique=False)

    op.create_table('notion_tasks',
    sa.Column('notion_page_id', sa.String(length=255), nullable=False),
    sa.Column('notion_database_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('discord_user_id', sa.String(length=20), nullable=False),
    sa.Column('discord_message_id', sa.String(length=20), nullable=True),
    sa.Column('discord_channel_id', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notion_url', sa.String(length=500), nullable=True),
    sa.Column('notion_properties', sa.JSON(), nullable=False),
    sa.Column('last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notion_page_id')
    )
    with op.batch_alter_table('notion_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notion_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notion_tasks_discord_user_id'), ['discord_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notion_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notion_tasks_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notion_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notion_tasks_title'))
        batch_op.drop_index(batch_op.f('ix_notion_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_notion_tasks_discord_user_id'))
        batch_op.drop_index(batch_op.f('ix_notion_tasks_created_at'))

    op.drop_table('notion_tasks')
    with op.batch_alter_table('notion_databases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notion_databases_id'))
        batch_op.drop_index(batch_op.f('ix_notion_databases_created_at'))

    op.drop_table('notion_databases')
    # ### end Alembic commands ###