"""Add ON_HOLD status to TaskStatus

Revision ID: a558643327c9
Revises: 4e1cfbea89e9
Create Date: 2025-08-26 14:32:15.580272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a558643327c9'
down_revision = '4e1cfbea89e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###