"""Initial database schema

Revision ID: a6a7cb1466f0
Revises: d2d1d808f846
Create Date: 2025-08-26 13:36:44.261068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a7cb1466f0'
down_revision = 'd2d1d808f846'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###