"""Initial database schema

Revision ID: d2d1d808f846
Revises: 
Create Date: 2025-08-26 13:35:53.581250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2d1d808f846'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_repositories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('default_branch', sa.String(length=100), nullable=False),
    sa.Column('discord_channel_id', sa.String(length=20), nullable=True),
    sa.Column('notification_channel_id', sa.String(length=20), nullable=True),
    sa.Column('webhook_url', sa.String(length=255), nullable=True),
    sa.Column('webhook_secret', sa.String(length=255), nullable=True),
    sa.Column('webhook_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('track_pushes', sa.Boolean(), nullable=False),
    sa.Column('track_pull_requests', sa.Boolean(), nullable=False),
    sa.Column('track_issues', sa.Boolean(), nullable=False),
    sa.Column('track_releases', sa.Boolean(), nullable=False),
    sa.Column('ignored_branches', sa.Text(), nullable=True),
    sa.Column('ignored_users', sa.Text(), nullable=True),
    sa.Column('total_commits', sa.Integer(), nullable=False),
    sa.Column('total_pull_requests', sa.Integer(), nullable=False),
    sa.Column('total_issues', sa.Integer(), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name')
    )
    with op.batch_alter_table('github_repositories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_github_repositories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_github_repositories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_github_repositories_name'), ['name'], unique=False)

    op.create_table('github_webhook_events',
    sa.Column('github_event_id', sa.String(length=100), nullable=True),
    sa.Column('delivery_id', sa.String(length=100), nullable=False),
    sa.Column('repository_name', sa.String(length=255), nullable=False),
    sa.Column('repository_full_name', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('sender_login', sa.String(length=100), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('sender_avatar', sa.String(length=255), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('commit_sha', sa.String(length=40), nullable=True),
    sa.Column('pull_request_number', sa.Integer(), nullable=True),
    sa.Column('issue_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discord_message_id', sa.String(length=20), nullable=True),
    sa.Column('discord_channel_id', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_id')
    )
    with op.batch_alter_table('github_webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_github_webhook_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_github_webhook_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_github_webhook_events_github_event_id'), ['github_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_github_webhook_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_github_webhook_events_repository_name'), ['repository_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('github_webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_github_webhook_events_repository_name'))
        batch_op.drop_index(batch_op.f('ix_github_webhook_events_id'))
        batch_op.drop_index(batch_op.f('ix_github_webhook_events_github_event_id'))
        batch_op.drop_index(batch_op.f('ix_github_webhook_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_github_webhook_events_created_at'))

    op.drop_table('github_webhook_events')
    with op.batch_alter_table('github_repositories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_github_repositories_name'))
        batch_op.drop_index(batch_op.f('ix_github_repositories_id'))
        batch_op.drop_index(batch_op.f('ix_github_repositories_created_at'))

    op.drop_table('github_repositories')
    # ### end Alembic commands ###