"""add_notion_projects_table_only

Revision ID: dc278095b4d2
Revises: df996dc5ec1b
Create Date: 2025-08-27 21:50:21.541823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc278095b4d2'
down_revision = '8d2f3135f920'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notion_projects',
    sa.Column('notion_page_id', sa.String(length=255), nullable=False),
    sa.Column('notion_database_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('discord_user_id', sa.String(length=20), nullable=True),
    sa.Column('discord_message_id', sa.String(length=20), nullable=True),
    sa.Column('discord_channel_id', sa.String(length=20), nullable=True),
    sa.Column('notion_url', sa.String(length=500), nullable=True),
    sa.Column('notion_properties', sa.JSON(), nullable=True),
    sa.Column('last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notion_page_id')
    )
    op.create_index(op.f('ix_notion_projects_discord_user_id'), 'notion_projects', ['discord_user_id'], unique=False)
    op.create_index(op.f('ix_notion_projects_title'), 'notion_projects', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notion_projects_title'), table_name='notion_projects')
    op.drop_index(op.f('ix_notion_projects_discord_user_id'), table_name='notion_projects')
    op.drop_table('notion_projects')
    # ### end Alembic commands ###